[build]
  base = "creative_infotech"           # points to your React app folder
  publish = "build"                    # relative to base folder
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--openssl-legacy-provider"
